# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector_pb2 as vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='imu.proto',
  package='sensor_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\timu.proto\x12\x0bsensor_msgs\x1a\x0cvector.proto\"\x90\x01\n\x06imu_st\x12&\n\x05\x61\x63\x63\x65l\x18\x01 \x01(\x0b\x32\x17.standard_msgs.vector_t\x12%\n\x04gyro\x18\x02 \x01(\x0b\x32\x17.standard_msgs.vector_t\x12$\n\x03mag\x18\x03 \x01(\x0b\x32\x17.standard_msgs.vector_t\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\"\x85\x01\n\x08image_st\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\r\x12\x12\n\ncompressed\x18\x04 \x01(\x08\x12\x10\n\x08\x65ncoding\x18\x05 \x01(\t\x12\x12\n\nimage_data\x18\x06 \x01(\x0c\x12\x11\n\ttimestamp\x18\x07 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[vector__pb2.DESCRIPTOR,])




_IMU_ST = _descriptor.Descriptor(
  name='imu_st',
  full_name='sensor_msgs.imu_st',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accel', full_name='sensor_msgs.imu_st.accel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='sensor_msgs.imu_st.gyro', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mag', full_name='sensor_msgs.imu_st.mag', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sensor_msgs.imu_st.timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=185,
)


_IMAGE_ST = _descriptor.Descriptor(
  name='image_st',
  full_name='sensor_msgs.image_st',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='sensor_msgs.image_st.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='sensor_msgs.image_st.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='sensor_msgs.image_st.depth', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compressed', full_name='sensor_msgs.image_st.compressed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='sensor_msgs.image_st.encoding', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='sensor_msgs.image_st.image_data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sensor_msgs.image_st.timestamp', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=321,
)

_IMU_ST.fields_by_name['accel'].message_type = vector__pb2._VECTOR_T
_IMU_ST.fields_by_name['gyro'].message_type = vector__pb2._VECTOR_T
_IMU_ST.fields_by_name['mag'].message_type = vector__pb2._VECTOR_T
DESCRIPTOR.message_types_by_name['imu_st'] = _IMU_ST
DESCRIPTOR.message_types_by_name['image_st'] = _IMAGE_ST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

imu_st = _reflection.GeneratedProtocolMessageType('imu_st', (_message.Message,), {
  'DESCRIPTOR' : _IMU_ST,
  '__module__' : 'imu_pb2'
  # @@protoc_insertion_point(class_scope:sensor_msgs.imu_st)
  })
_sym_db.RegisterMessage(imu_st)

image_st = _reflection.GeneratedProtocolMessageType('image_st', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE_ST,
  '__module__' : 'imu_pb2'
  # @@protoc_insertion_point(class_scope:sensor_msgs.image_st)
  })
_sym_db.RegisterMessage(image_st)


# @@protoc_insertion_point(module_scope)
