# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nav_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector_pb2 as vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nav_msgs.proto',
  package='nav_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0enav_msgs.proto\x12\x08nav_msgs\x1a\x0cvector.proto\"y\n\x07pose_st\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.standard_msgs.vector_t\x12\x30\n\x0borientation\x18\x02 \x01(\x0b\x32\x1b.standard_msgs.quaternion_t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[vector__pb2.DESCRIPTOR,])




_POSE_ST = _descriptor.Descriptor(
  name='pose_st',
  full_name='nav_msgs.pose_st',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='nav_msgs.pose_st.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='nav_msgs.pose_st.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nav_msgs.pose_st.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=163,
)

_POSE_ST.fields_by_name['position'].message_type = vector__pb2._VECTOR_T
_POSE_ST.fields_by_name['orientation'].message_type = vector__pb2._QUATERNION_T
DESCRIPTOR.message_types_by_name['pose_st'] = _POSE_ST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pose_st = _reflection.GeneratedProtocolMessageType('pose_st', (_message.Message,), {
  'DESCRIPTOR' : _POSE_ST,
  '__module__' : 'nav_msgs_pb2'
  # @@protoc_insertion_point(class_scope:nav_msgs.pose_st)
  })
_sym_db.RegisterMessage(pose_st)


# @@protoc_insertion_point(module_scope)
