# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vector.proto',
  package='standard_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cvector.proto\x12\rstandard_msgs\"+\n\x08vector_t\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\":\n\x0cquaternion_t\x12\t\n\x01w\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\"\\\n\x07twist_t\x12\'\n\x06linear\x18\x01 \x01(\x0b\x32\x17.standard_msgs.vector_t\x12(\n\x07\x61ngualr\x18\x02 \x01(\x0b\x32\x17.standard_msgs.vector_t\"\\\n\x08wrench_t\x12&\n\x05\x61\x63\x63\x65l\x18\x01 \x01(\x0b\x32\x17.standard_msgs.vector_t\x12(\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x17.standard_msgs.vector_tb\x06proto3')
)




_VECTOR_T = _descriptor.Descriptor(
  name='vector_t',
  full_name='standard_msgs.vector_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='standard_msgs.vector_t.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='standard_msgs.vector_t.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='standard_msgs.vector_t.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=74,
)


_QUATERNION_T = _descriptor.Descriptor(
  name='quaternion_t',
  full_name='standard_msgs.quaternion_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='standard_msgs.quaternion_t.w', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='standard_msgs.quaternion_t.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='standard_msgs.quaternion_t.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='standard_msgs.quaternion_t.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=134,
)


_TWIST_T = _descriptor.Descriptor(
  name='twist_t',
  full_name='standard_msgs.twist_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='standard_msgs.twist_t.linear', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angualr', full_name='standard_msgs.twist_t.angualr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=228,
)


_WRENCH_T = _descriptor.Descriptor(
  name='wrench_t',
  full_name='standard_msgs.wrench_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accel', full_name='standard_msgs.wrench_t.accel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular', full_name='standard_msgs.wrench_t.angular', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=322,
)

_TWIST_T.fields_by_name['linear'].message_type = _VECTOR_T
_TWIST_T.fields_by_name['angualr'].message_type = _VECTOR_T
_WRENCH_T.fields_by_name['accel'].message_type = _VECTOR_T
_WRENCH_T.fields_by_name['angular'].message_type = _VECTOR_T
DESCRIPTOR.message_types_by_name['vector_t'] = _VECTOR_T
DESCRIPTOR.message_types_by_name['quaternion_t'] = _QUATERNION_T
DESCRIPTOR.message_types_by_name['twist_t'] = _TWIST_T
DESCRIPTOR.message_types_by_name['wrench_t'] = _WRENCH_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

vector_t = _reflection.GeneratedProtocolMessageType('vector_t', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR_T,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:standard_msgs.vector_t)
  })
_sym_db.RegisterMessage(vector_t)

quaternion_t = _reflection.GeneratedProtocolMessageType('quaternion_t', (_message.Message,), {
  'DESCRIPTOR' : _QUATERNION_T,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:standard_msgs.quaternion_t)
  })
_sym_db.RegisterMessage(quaternion_t)

twist_t = _reflection.GeneratedProtocolMessageType('twist_t', (_message.Message,), {
  'DESCRIPTOR' : _TWIST_T,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:standard_msgs.twist_t)
  })
_sym_db.RegisterMessage(twist_t)

wrench_t = _reflection.GeneratedProtocolMessageType('wrench_t', (_message.Message,), {
  'DESCRIPTOR' : _WRENCH_T,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:standard_msgs.wrench_t)
  })
_sym_db.RegisterMessage(wrench_t)


# @@protoc_insertion_point(module_scope)
